// Install Playwright separately, or point PLAYWRIGHT_MODULE at an existing package.
import { createRequire } from 'node:module';
import { mkdir, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { saveAndResume } from './editor-checkpoint.mjs';
import { editorData } from '../src/editor-data.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_PATH ? { executablePath: process.env.BROWSER_PATH } : {}) });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, acceptDownloads: true });
const page = await context.newPage();
const failures = [];
page.on('pageerror', e => failures.push(e.message));
const root = new URL('?method=tablet-drop', process.env.APP_URL || 'http://127.0.0.1:4173/').href;
const key = 'poe2-farming.personal.v1';
await mkdir('test-results', { recursive: true });
try {
  await page.goto(root);
  await page.getByRole('heading', { name: '서판 수집 파밍', exact: true }).waitFor();
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
  const term = page.locator('#content [data-term="mountain-mastery"]').first();
  await term.focus();
  await page.getByRole('dialog', { name: '산 숙련 설명' }).waitFor();
  assert.match(await page.locator('.term-card').innerText(), /75레벨/);
  assert.match(await page.locator('.term-card .chosen').innerText(), /서판의 수량 50%/);
  await page.keyboard.press('ArrowDown');
  assert.equal(await page.locator('.close-term').evaluate(el => el === document.activeElement), true);
  await page.keyboard.press('Escape'); assert.equal(await page.locator('.term-card').count(), 0);
  await page.getByRole('button', { name: '내 데이터로 복사' }).click();
  await page.getByLabel('파밍법 이름 (필수)').fill('나의 서판 세팅');
  await page.getByLabel('개수 (1~4)', { exact: true }).fill('2');
  await page.getByLabel('나의 메모', { exact: true }).fill('원본과 분리된 나의 메모');
  const quantity = editorData.modifiers.find(m => m.metric === 'waystoneQuantity' && m.numeric && m.tablets.includes('방사능 노출 서판'));
  await page.getByLabel('서판 속성', { exact: true }).first().selectOption(quantity.id);
  await page.getByLabel('목표 수치', { exact: true }).first().fill('40');
  assert.match(await page.locator('.option-summary').first().innerText(), /40%/);
  await saveAndResume(page);
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), key);
  assert.equal(saved.records[0].method.tablets.items[0].count, 2);
  await page.getByLabel('개수 (1~4)', { exact: true }).fill('-1');
  assert.equal(await page.locator('#form-errors').isVisible(), true);
  assert.equal(await page.evaluate(key => JSON.parse(localStorage.getItem(key)).records[0].method.tablets.items[0].count, key), 2);
  await page.getByLabel('개수 (1~4)', { exact: true }).fill(''); await saveAndResume(page);
  assert.equal(await page.evaluate(key => JSON.parse(localStorage.getItem(key)).records[0].method.tablets.items[0].count, key), null);
  await page.getByLabel('개수 (1~4)', { exact: true }).fill('2');
  await page.getByRole('button', { name: '＋ 서판 행 추가', exact: true }).click();
  assert.equal(await page.getByLabel('공식 서판 명칭', { exact: true }).count(), 2);
  await page.getByLabel('공식 서판 명칭', { exact: true }).nth(1).selectOption('의식 서판');
  const ritual = editorData.modifiers.find(m => m.tablets.includes('의식 서판'));
  await page.getByLabel('서판 속성 추가', { exact: true }).nth(1).selectOption(ritual.id);
  await page.getByRole('button', { name: '현재 입력 미리보기', exact: true }).click();
  assert.ok((await page.locator('#preview-body').innerText()).includes(ritual.text)); await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '저장', exact: true }).first().click();
  await page.reload();
  await page.locator('#workspace-switch').click(); await page.getByRole('button').filter({ hasText: '나의 서판 세팅' }).click();
  assert.match(await page.locator('#content').innerText(), /원본과 분리된 나의 메모/);
  await page.locator('#workspace-switch').click(); await page.locator('[data-select="base"]').click();
  assert.match(await page.locator('.tablet-heading').innerText(), /3개/);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'JSON 내보내기' }).click();
  const download = await downloadPromise; await download.saveAs('test-results/backup.personal.json');
  const backup = await readFile('test-results/backup.personal.json', 'utf8');
  await page.evaluate(key => localStorage.removeItem(key), key); await page.reload();
  await page.getByRole('button', { name: '가져오기', exact: true }).click();
  await page.locator('#backup-file').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{') });
  await page.getByText('JSON 문법이 올바르지 않습니다.', { exact: false }).waitFor();
  assert.equal(await page.locator('#confirm-import').isDisabled(), true);
  await page.locator('#backup-file').setInputFiles('test-results/backup.personal.json');
  await page.getByText('검증 완료', { exact: false }).waitFor();
  await page.getByRole('button', { name: '검증한 자료 복원' }).click();
  const restored = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), key);
  assert.deepEqual(restored, JSON.parse(backup));
  await page.route('**/data/library.ko.json', async route => {
    const response = await route.fetch(); const data = await response.json();
    data.strategies.find(m => m.id === 'tablet-drop').tablets.items[0].count = 4;
    await route.fulfill({ json: data });
  });
  await page.reload();
  await page.locator('#workspace-switch').click();
  await page.getByRole('button').filter({ hasText: '나의 서판 세팅' }).click();
  await page.getByText('기본 자료가 복사 이후 변경되었습니다.', { exact: false }).waitFor();
  assert.deepEqual(await page.evaluate(key => JSON.parse(localStorage.getItem(key)), key), JSON.parse(backup));
  await page.unroute('**/data/library.ko.json');
  await page.locator('#workspace-switch').click();
  await page.getByRole('button', { name: '새 파밍법' }).click();
  await page.getByLabel('파밍법 이름 (필수)').fill('<img src=x onerror=alert(1)>');
  await page.getByRole('button', { name: '저장', exact: true }).first().click();
  assert.equal(await page.locator('#content img').count(), 0);
  await page.evaluate(key => localStorage.setItem(key, '{broken'), key); await page.reload();
  await page.getByRole('button', { name: '기존 저장 원문 백업' }).waitFor();
  assert.equal(await page.evaluate(key => localStorage.getItem(key), key), '{broken');
  await page.getByRole('button', { name: '가져오기', exact: true }).click();
  await page.locator('#backup-file').setInputFiles('test-results/backup.personal.json');
  await page.getByText('검증 완료', { exact: false }).waitFor();
  await page.getByRole('button', { name: '검증한 자료 복원' }).click();
  assert.deepEqual(await page.evaluate(key => JSON.parse(localStorage.getItem(key)), key), JSON.parse(backup));

  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const mobilePage = await mobile.newPage();
  mobilePage.on('pageerror', e => failures.push(e.message));
  await mobilePage.goto(root);
  await mobilePage.getByRole('heading', { name: '서판 수집 파밍', exact: true }).waitFor();
  assert.equal(await mobilePage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await mobilePage.locator('.tablet-heading .term-link').first().tap();
  await mobilePage.getByRole('dialog', { name: '방사능 노출 서판 설명' }).waitFor();
  assert.equal(await mobilePage.locator('.term-card a').getAttribute('target'), '_blank');
  await mobilePage.getByRole('button', { name: '용어 설명 닫기' }).tap();
  await mobilePage.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  await mobilePage.getByRole('button', { name: '내 데이터로 복사' }).tap();
  await mobilePage.getByLabel('개수 (1~4)', { exact: true }).fill('1');
  assert.equal(await mobilePage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await mobilePage.getByRole('button', { name: '＋ 서판 행 추가', exact: true }).tap();
  await mobilePage.getByLabel('공식 서판 명칭', { exact: true }).nth(1).selectOption('탐험 서판');
  await mobilePage.getByRole('button', { name: '현재 입력 미리보기', exact: true }).tap();
  assert.match(await mobilePage.locator('#preview-body').innerText(), /탐험 서판/);
  await mobilePage.screenshot({ path: 'test-results/mobile-editor.png', fullPage: true });
  await mobile.close();

  const quotaPage = await context.newPage();
  await quotaPage.goto(root); await quotaPage.getByRole('heading', { name: '서판 수집 파밍', exact: true }).waitFor();
  await quotaPage.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota exceeded', 'QuotaExceededError'); }; });
  await quotaPage.getByRole('button', { name: '내 데이터로 복사' }).click();
  await quotaPage.locator('[data-action="finish"]').first().click();
  assert.match(await quotaPage.locator('#save-status').innerText(), /저장 실패/);
  assert.equal(await quotaPage.locator('#storage-warning').isVisible(), true);
  await quotaPage.close();
  const tab2 = await context.newPage(); await tab2.goto(root);
  await tab2.getByRole('heading', { name: '서판 수집 파밍', exact: true }).waitFor();
  await page.locator('#workspace-switch').click();
  await page.getByRole('button', { name: '새 파밍법' }).click();
  await page.locator('[data-action="finish"]').first().click();
  await tab2.getByText('다른 탭에서 개인 자료가 변경되었습니다.', { exact: false }).waitFor();
  const latest = await page.evaluate(key => localStorage.getItem(key), key);
  await tab2.getByRole('button', { name: '내 데이터로 복사' }).click();
  await tab2.locator('[data-action="finish"]').first().click();
  assert.match(await tab2.locator('#save-status').innerText(), /저장 실패/);
  assert.equal(await page.evaluate(key => localStorage.getItem(key), key), latest);
  await tab2.close();
  assert.deepEqual(failures, []);
  console.log('PASS: desktop, keyboard tooltip, editing, validation, refresh, seed isolation/update, export/import, recovery, XSS, mobile touch and layout, quota and cross-tab protection');
} finally { await browser.close(); }
