import { createRequire } from 'node:module';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_PATH ? { executablePath: process.env.BROWSER_PATH } : {}) });
const root = process.env.APP_URL || 'http://127.0.0.1:4173/';
const seed = JSON.parse(await readFile('data/library.ko.json', 'utf8'));
const key = 'poe2-farming.personal.v1';
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
const page = await context.newPage(); page.setDefaultTimeout(10000);
const failures = []; page.on('pageerror', e => failures.push(e.message));
const card = (id, p = page) => p.locator(`.browse-grid [data-select="${id === 'tablet-drop' ? 'base' : `base:${id}`}"]`);
const compareButton = (id, p = page) => p.locator(`.browse-grid [data-compare="${id === 'tablet-drop' ? 'base' : `base:${id}`}"]`);
const openLibrary = async (p = page) => { if (!await p.locator('.sidebar').isVisible()) await p.locator('.top-nav [data-page="library"]').click(); };
const choose = async (id,p = page) => { await openLibrary(p); await p.locator('#search').fill(''); await card(id,p).click(); };
const filter = key => page.locator(`[data-filter="${key}"]`);
await mkdir('test-results', { recursive: true });
try {
  await page.goto(new URL('?method=tablet-drop', root).href);
  await page.getByRole('heading', { name: '서판 수집 파밍', exact: true }).waitFor();
  assert.equal(await page.locator('#workspace-switch, #list, .switcher-close').count(), 0);
  await openLibrary();
  assert.equal(await page.locator('.browse-card').count(), seed.strategies.length);
  for (const method of seed.strategies) {
    await choose(method.id);
    assert.equal(new URL(page.url()).searchParams.get('method'), method.id);
    await page.getByRole('heading', { name: method.name, exact: true }).waitFor();
    const content = await page.locator('#content').innerText();
    assert.match(content, /검증된 시간당 순이익: 미확인/);
    assert.ok(content.includes(method.reportedResults.text));
    for (const c of method.constraints) assert.ok(content.includes(c.text));
    assert.doesNotMatch(content, /제작자 정정|정정 전 설명/);
    for (const c of method.constraints.filter(c => c.sourceUrl)) assert.equal(await page.locator('#content a').filter({ hasText: '참고 자료' }).evaluateAll(links => links.map(a => a.href)).then(urls => urls.includes(c.sourceUrl)), true);
    assert.doesNotMatch(content, /제작·판매|지도 파밍/);
    assert.equal(await page.locator('[data-filter="kind"]').count(), 0);
    await page.getByRole('button', { name: '내 데이터로 복사' }).click();
    await page.getByLabel('파밍법 이름 (필수)').fill(`개인 ${method.name}`);
    await page.getByLabel('나의 메모', { exact: true }).fill(`${method.id} 보관 메모`);
    assert.equal(await page.locator('#form-errors').isVisible(), false);
    await page.getByRole('button', { name: '저장', exact: true }).first().click();
    await page.getByRole('heading', { name: `개인 ${method.name}`, exact: true }).waitFor();
    assert.equal(new URL(page.url()).search, '', 'private IDs or contents must not be placed in shareable URL');
  }
  const data = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), key);
  assert.equal(data.records.length, seed.strategies.length); assert.equal(data.schemaVersion, 6);
  for (const r of data.records) {
    const original = seed.strategies.find(m => m.id === r.originId);
    assert.deepEqual(r.method.constraints, original.constraints);
    assert.deepEqual(r.method.reportedResults, original.reportedResults);
    assert.deepEqual(r.method.atlas, original.atlas);
    assert.deepEqual(r.method.creatorGuide, original.creatorGuide);
    assert.deepEqual(r.sources, seed.sources.filter(s => s.id === original.sourceVideoId || (original.supportingVideoIds || []).includes(s.id)));
    assert.deepEqual(r.method.evidenceReview, original.evidenceReview);
    assert.deepEqual(r.method.supportingVideoIds, original.supportingVideoIds);
    assert.equal(r.method.notes, `${r.originId} 보관 메모`);
  }
  await page.reload(); await page.getByRole('heading', { name: `개인 ${seed.strategies.at(-1).name}`, exact: true }).waitFor();
  await openLibrary(); await page.locator('[data-scope="base"]').click();
  await page.locator('.filter-panel summary').click();
  await filter('content').selectOption('대탐험'); await filter('investment').selectOption('low'); await filter('patch').selectOption('__unknown');
  assert.equal(await page.locator('.browse-card').count(), 1);
  assert.ok((await page.locator('.browse-grid').innerText()).includes('대탐험 상자 파밍'));
  await filter('master').selectOption('힐다'); assert.equal(await page.locator('.browse-card').count(), 0);
  await page.locator('.library-empty [data-action="reset-filters"]').click();
  await filter('master').selectOption('__unknown'); assert.equal(await page.locator('.browse-card').count(), 2);
  await page.locator('#filters [data-action="reset-filters"]').click();
  await page.locator('[data-scope="base"]').click();
  await compareButton('tablet-drop').focus(); await page.keyboard.press('Enter');
  assert.equal(await compareButton('tablet-drop').evaluate(el => el === document.activeElement), true, 'keyboard comparison selection should retain focus');
  await compareButton('grand-expedition-chests').click(); await compareButton('cleansed-fracturing').click();
  await compareButton('abyss-currency').click();
  assert.match(await page.locator('#toast').innerText(), /최대 3개/);
  assert.equal(await page.locator('#compare-tray .compare-chips button').count(), 3);
  await page.locator('#search').fill('검색결과없음');
  assert.equal(await page.locator('#compare-tray .compare-chips button').count(), 3);
  await page.locator('#compare-tray [data-action="compare"]').click();
  await page.getByRole('heading', { name: '파밍법 비교', exact: true }).waitFor();
  assert.equal(await page.locator('thead th').count(), 4); await page.locator('#comparison-details').check();
  assert.ok((await page.locator('[data-row="monsterRarity"]').innerText()).includes('100 이상 (%)'));
  assert.ok((await page.locator('[data-row="waystoneQuantity"]').innerText()).includes('35%'));
  const differentCount = await page.locator('tbody tr.different').count();
  await page.getByLabel('차이만 보기', { exact: true }).check();
  assert.equal(await page.locator('tbody tr[data-row]').count(), differentCount);
  assert.equal(await page.locator('tbody tr[data-row]:not(.different)').count(), 0);
  await page.getByLabel('차이만 보기', { exact: true }).uncheck();
  await page.getByRole('button', { name: '비교 주소 공유' }).click();
  const shared = await page.locator('#share-url').inputValue();
  assert.equal(new URL(shared).searchParams.getAll('compare').length, 3);
  assert.match(await page.locator('#share-note').innerText(), /로컬 주소/);
  await page.getByRole('button', { name: '공유 창 닫기' }).click();
  await page.locator('#main').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'test-results/catalog-comparison.png' });
  const second = await context.newPage(); await second.goto(shared); await second.getByRole('heading', { name: '파밍법 비교', exact: true }).waitFor();
  assert.equal(await second.locator('thead th').count(), 4); await second.reload(); await second.getByRole('heading', { name: '파밍법 비교', exact: true }).waitFor();
  await second.close();
  await choose('ritual-nameless-cycle'); await choose('abyss-currency');
  await page.goBack(); await page.locator('.browse-card').first().waitFor();
  await page.goBack(); await page.getByRole('heading', { name: '이름 없는 자의 의례 파밍', exact: true }).waitFor();
  await page.goForward(); await page.locator('.browse-card').first().waitFor();
  await page.goForward(); await page.getByRole('heading', { name: '심연 화폐 파밍', exact: true }).waitFor();
  await page.reload(); await page.getByRole('heading', { name: '심연 화폐 파밍', exact: true }).waitFor();
  await page.locator('#compare-tray [data-action="clear-compare"]').click();
  await openLibrary(); await compareButton('tablet-drop').click();
  await page.locator('[data-scope="all"]').click();
  const own = data.records.find(r => r.originId === 'tablet-drop');
  await page.locator(`.browse-grid [data-compare="${own.id}"]`).click(); await page.locator('#compare-tray [data-action="compare"]').click();
  assert.ok(await page.locator('tbody tr[data-row]').count() > 0);
  await page.getByLabel('차이만 보기', { exact: true }).check();
  assert.equal(await page.locator('tbody tr[data-row]').count(), 0, 'a personal copy with only a changed name and memo has the same setup');
  await page.getByLabel('차이만 보기', { exact: true }).uncheck();
  assert.equal(await page.getByRole('button', { name: '비교 주소 공유' }).count(), 0);
  assert.equal(new URL(page.url()).search, '');
  await page.goto(new URL('?method=not-found', root).href); await page.getByRole('heading', { name: '주소를 확인해주세요' }).waitFor();
  await page.getByRole('button', { name: '홈으로 이동' }).click(); await page.locator('.home-hero').waitFor();

  // A real v1 storage record is upgraded in memory without discarding any personal changes.
  const legacyRecord = structuredClone(own); delete legacyRecord.method.content; delete legacyRecord.method.tablets.usage;
  const legacyRaw = JSON.stringify({ format: 'poe2-farming-personal', schemaVersion: 1, records: [legacyRecord] });
  const legacyContext = await browser.newContext(); const legacyPage = await legacyContext.newPage();
  legacyPage.setDefaultTimeout(10000);
  legacyPage.on('pageerror', e => { failures.push(e.message); console.error('Legacy page:', e.stack); });
  await legacyPage.addInitScript(({ key, raw }) => localStorage.setItem(key, raw), { key, raw: legacyRaw });
  await legacyPage.goto(new URL('?method=tablet-drop', root).href); await legacyPage.getByRole('heading', { name: '서판 수집 파밍', exact: true }).waitFor();
  assert.equal(await legacyPage.evaluate(key => JSON.parse(localStorage.getItem(key)).schemaVersion, key), 6);
  await openLibrary(legacyPage); await legacyPage.locator(`.browse-grid [data-select="${own.id}"]`).click(); await legacyPage.getByRole('button', { name: '세팅 편집' }).click();
  await legacyPage.screenshot({ path: 'test-results/legacy-editor.png' });
  await legacyPage.getByLabel('나의 메모', { exact: true }).fill('버전 1에서 유지한 메모');
  await legacyPage.locator('[data-action="finish"]').first().click();
  assert.equal(await legacyPage.evaluate(key => JSON.parse(localStorage.getItem(key)).schemaVersion, key), 6);
  await legacyContext.close();

  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const mobilePage = await mobile.newPage(); mobilePage.on('pageerror', e => failures.push(e.message));
  await mobilePage.goto(shared); await mobilePage.getByRole('heading', { name: '파밍법 비교', exact: true }).waitFor();
  assert.equal(await mobilePage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  const scroller = mobilePage.getByRole('region', { name: '파밍법 비교표' });
  assert.equal(await scroller.evaluate(el => el.scrollWidth <= el.clientWidth), true);
  const values = mobilePage.locator('tr[data-row]').first().locator('td');
  const firstValue = await values.nth(0).boundingBox(), secondValue = await values.nth(1).boundingBox();
  assert.ok(secondValue.y >= firstValue.y + firstValue.height - 1 && Math.abs(firstValue.x - secondValue.x) < 1);
  assert.equal(await values.nth(1).locator('.mobile-comparison-name').isVisible(), true);
  await mobilePage.locator('#main').evaluate(el => el.scrollIntoView({ block: 'start', behavior: 'instant' }));
  await mobilePage.screenshot({ path: 'test-results/catalog-mobile.png' });
  await mobile.close();
  assert.deepEqual(failures, []);
  console.log('PASS: all library detail/copy/edit flows, source fidelity, filters, comparison limit/differences, private data separation, share reload/history, v1 migration and mobile comparison');
} catch (error) {
  await page.screenshot({ path: 'test-results/catalog-failure.png' });
  console.error(await page.locator('#content').innerText()); throw error;
} finally { await browser.close(); }
