import { saveAndResume } from './editor-checkpoint.mjs';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { editorData } from '../src/editor-data.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_PATH ? { executablePath: process.env.BROWSER_PATH } : {}) });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
const page = await context.newPage(); page.setDefaultTimeout(10000);
const root = process.env.APP_URL || 'http://127.0.0.1:4173/';
const errors = []; page.on('pageerror', e => errors.push(e.message));
const key = 'poe2-farming.personal.v1';
const method = async () => { await saveAndResume(page); return (await page.evaluate(k => JSON.parse(localStorage.getItem(k)), key)).records[0].method; };
try {
  await page.goto(new URL('?view=library', root).href);
  await page.getByRole('button', { name: '새 파밍법' }).click();
  await page.getByLabel('파밍법 이름 (필수)').fill('선택형 세팅');
  assert.equal(await page.getByLabel('적용 패치', { exact: true }).evaluate(el => el.tagName), 'SELECT');
  await page.getByLabel('적용 패치', { exact: true }).selectOption('0.5.5');
  await page.getByLabel('비용', { exact: true }).fill('2.5');
  await page.getByLabel('단위', { exact: true }).selectOption('신성한 오브');
  assert.equal(await page.locator('[data-path="method.party"]').count(), 0);
  assert.equal(await page.locator('#editor textarea[data-type="lines"]').count(), 0);
  await page.getByLabel('목적 추가', { exact: true }).fill('서판 수집'); await page.getByLabel('목적 추가', { exact: true }).press('Enter');
  await page.getByLabel('준비물 추가', { exact: true }).evaluate(el => {
    const data = new DataTransfer(); data.setData('text/plain', '준비물 A\n준비물 B');
    el.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }));
  });
  assert.deepEqual((await method()).supplies, ['준비물 A','준비물 B']);
  await page.locator('[data-op="remove"][data-path="method.supplies.0"]').click();
  assert.deepEqual((await method()).supplies, ['준비물 B']);
  await page.getByRole('button', { name: '＋ 서판 행 추가', exact: true }).click();
  await page.getByLabel('공식 서판 명칭', { exact: true }).selectOption('의식 서판');
  const mod = editorData.modifiers.find(m => m.metric === 'omenChance');
  await page.getByLabel('서판 속성 추가', { exact: true }).selectOption(mod.id);
  await page.getByLabel('목표 수치', { exact: true }).fill('60');
  assert.equal((await method()).tablets.items[0].options[0].modifierId, mod.id);
  assert.match((await method()).tablets.items[0].options[0].text, /60%/);
  assert.equal(await page.locator(`[data-add-modifier] option[value="${mod.id}"]`).count(), 0);
  await page.getByLabel('경로석 등급', { exact: true }).selectOption('16');
  await page.getByLabel('속성 수', { exact: true }).selectOption('8');
  assert.equal(await page.getByLabel('경로석 등급', { exact: true }).locator('option[value="17"]').count(), 0);
  assert.equal((await method()).waystone.tier, 16);
  await page.getByLabel('경로석 등급', { exact: true }).selectOption('16');
  assert.equal(await page.getByLabel('속성 수', { exact: true }).locator('option[value="9"]').count(), 0);
  assert.equal((await method()).waystone.affixCount, 8);
  await page.getByLabel('속성 수', { exact: true }).selectOption('8');
  await page.locator('[data-check-path="method.map.regions"][value="강변"]').check();
  const mountain = page.locator('[data-check-path="method.map.biomes"][value="산"]');
  await mountain.check(); await mountain.uncheck(); assert.deepEqual((await method()).map.biomes, []); await mountain.check();
  await page.getByRole('button', { name: '＋ 노드 추가', exact: true }).click();
  await page.getByLabel('아틀라스 노드', { exact: true }).selectOption('선택받은 길');
  await page.getByLabel('선택 효과', { exact: true }).selectOption('아즈메리 혼백');
  await page.getByRole('button', { name: '＋ 대가 구성 추가', exact: true }).click();
  await page.getByLabel('대가', { exact: true }).selectOption('힐다');
  const ability = page.locator('[data-master-path][value="HildaKeystone8"]');
  await ability.focus(); await page.keyboard.press('Space');
  assert.equal((await method()).masters.choices[0].nodes[0].name, '고대 명문');
  assert.equal(await page.locator('[data-master-path][value="JadoKeystone1"]').count(), 0);
  await page.locator('.master-editor').screenshot({ path: 'test-results/master-picker.png' });
  await page.locator('#main').evaluate(el => el.scrollIntoView({ behavior: 'instant' }));
  await page.screenshot({ path: 'test-results/editor-choice-desktop.png' });
  await page.getByRole('button', { name: '저장', exact: true }).first().click();
  assert.ok((await page.locator('#content').innerText()).includes('2.5 신성한 오브 / 지도 1회당'));
  const saved = await method(); await page.reload(); await page.getByRole('button', { name: '세팅 편집' }).click();
  assert.deepEqual(await method(), saved);
  assert.equal(await page.getByLabel('목표 수치', { exact: true }).inputValue(), '60');
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const mp = await mobile.newPage(); mp.on('pageerror', e => errors.push(e.message));
  await mp.goto(new URL('?view=library', root).href); await mp.getByRole('button', { name: '새 파밍법' }).tap();
  await mp.getByRole('button', { name: '＋ 대가 구성 추가', exact: true }).tap();
  await mp.getByLabel('대가', { exact: true }).selectOption('도리아니');
  await mp.locator('[data-master-path][value="DoryaniKeystone1"]').tap();
  assert.equal(await mp.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await mp.locator('.master-editor').screenshot({ path: 'test-results/master-picker-mobile.png' });
  await mobile.close(); assert.deepEqual(errors, []);
  console.log('PASS: selection editor, numeric budget, item rows, modifier IDs, limits, region/biome checks, atlas effects, master abilities, persistence, keyboard and mobile');
} catch (error) { await page.screenshot({ path: 'test-results/editor-failure.png', fullPage: true }); throw error; }
finally { await browser.close(); }
