import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const seed = JSON.parse(readFileSync('data/library.ko.json', 'utf8'));
const mapCount = seed.strategies.length;
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_PATH ? { executablePath: process.env.BROWSER_PATH } : {}) });
const root = process.env.APP_URL || 'http://127.0.0.1:4173/';
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
const page = await context.newPage(); page.setDefaultTimeout(10000);
const errors = []; page.on('pageerror', e => errors.push(e.message));
const crumb = name => page.getByRole('navigation', { name: '현재 위치' }).getByRole('link', { name, exact: true });
const home = () => page.locator('.top-nav [data-page="home"]').click();
await mkdir('test-results', { recursive: true });
try {
  await page.goto(root); await page.locator('.home-hero').waitFor();
  assert.equal(await page.locator('.sidebar').isVisible(), false);
  assert.equal(await page.locator('.category-card').count(), 2);
  await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true });
  await page.locator('.category-card [data-target-scope=""]').click();
  await page.getByRole('heading', { name: '파밍 라이브러리', exact: true, level: 2 }).waitFor();
  assert.equal(await page.locator('#content .browse-card').count(), mapCount);
  assert.equal(await page.locator('#filters [data-filter="kind"]').count(), 0);
  const categoryUrl = page.url();
  await page.reload(); await page.getByRole('heading', { name: '파밍 라이브러리', exact: true, level: 2 }).waitFor();
  const tab = await context.newPage(); await tab.goto(categoryUrl);
  await tab.getByRole('heading', { name: '파밍 라이브러리', exact: true, level: 2 }).waitFor();
  assert.equal(await tab.locator('#content .browse-card').count(), mapCount); await tab.close();
  await page.locator('#search').fill('서판 수집');
  assert.equal(await page.locator('#content .browse-card').count(), 1);
  await page.locator('#content a[data-select="base"]').click();
  await page.getByRole('heading', { name: '서판 수집 파밍', exact: true }).waitFor();
  assert.equal(await page.locator('.breadcrumb [aria-current="page"]').innerText(), '서판 수집 파밍');
  await page.goBack(); await page.getByRole('heading', { name: '파밍 라이브러리', exact: true, level: 2 }).waitFor();
  assert.equal(await page.locator('#search').inputValue(), '서판 수집');
  assert.equal(await page.locator('#content .browse-card').count(), 1);
  await page.goForward(); await crumb('파밍 라이브러리').focus(); await page.keyboard.press('Enter');
  await page.getByRole('heading', { name: '파밍 라이브러리', exact: true, level: 2 }).waitFor();
  assert.equal(await page.locator('#content .browse-card').count(), mapCount);
  assert.equal(await page.locator('.breadcrumb li').count(), 2);
  assert.doesNotMatch(await page.locator('#content').innerText(), /제작·판매|지도 파밍/);
  await crumb('홈').click(); await page.locator('.home-hero').waitFor();
  await page.locator('.category-card [data-target-scope="personal"]').click();
  await page.getByRole('heading', { name: '아직 저장한 개인 세팅이 없습니다.' }).waitFor();
  await page.locator('.top-nav [data-page="library"]').click();
  await page.locator('#content a[data-select="base"]').click();
  await page.getByRole('button', { name: '내 데이터로 복사' }).click();
  await page.getByLabel('파밍법 이름 (필수)').fill('');
  await crumb('내 데이터').click();
  assert.equal(await page.locator('#editor').isVisible(), true, 'invalid edits must block breadcrumb navigation');
  await page.getByLabel('파밍법 이름 (필수)').fill('내 이동 테스트');
  await page.getByLabel('나의 메모', { exact: true }).fill('이동해도 유지되는 메모');
  await page.locator('[data-action="finish"]').first().click();
  await crumb('내 데이터').click();
  assert.equal(await page.locator('#content .browse-card').count(), 1);
  await page.locator('#content .browse-card h3 a').click();
  await page.getByRole('heading', { name: '내 이동 테스트', exact: true }).waitFor();
  assert.ok((await page.locator('#content').innerText()).includes('이동해도 유지되는 메모'));
  assert.equal(new URL(page.url()).search, '');
  await crumb('내 데이터').click(); await home(); await page.reload(); await page.locator('.home-hero').waitFor();
  assert.equal(new URL(page.url()).pathname, new URL(root).pathname);
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const mp = await mobile.newPage(); mp.on('pageerror', e => errors.push(e.message));
  await mp.goto(root); await mp.locator('.home-hero').waitFor();
  assert.equal(await mp.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await mp.screenshot({ path: 'test-results/home-mobile.png', fullPage: true });
  await mp.locator('.category-card [data-target-scope=""]').tap();
  await mp.locator('#content a[data-select="base"]').tap();
  await mp.getByRole('navigation', { name: '현재 위치' }).getByRole('link', { name: '파밍 라이브러리', exact: true }).tap();
  await mp.getByRole('heading', { name: '파밍 라이브러리', exact: true, level: 2 }).waitFor();
  assert.equal(await mp.locator('#content .browse-card').count(), mapCount);
  assert.equal(await mp.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await mp.screenshot({ path: 'test-results/library-mobile.png', fullPage: true });
  await mobile.close(); assert.deepEqual(errors, []);
  console.log('PASS: home, category pages, breadcrumbs, keyboard/touch, reload/new tabs/history, filter restoration and personal edit preservation');
} catch (error) { await page.screenshot({ path: 'test-results/navigation-failure.png', fullPage: true }); throw error; }
finally { await browser.close(); }
