import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url), {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH ? {executablePath:process.env.BROWSER_PATH} : {})});
const root=process.env.APP_URL || 'http://127.0.0.1:4173/';
const errors=[], measurements=[];
try {
  for (const width of [1265,960,390,320]) {
    const context=await browser.newContext({viewport:{width,height:width<700?844:720},isMobile:width<700,hasTouch:width<700});
    const page=await context.newPage(); page.setDefaultTimeout(10000); page.on('pageerror',e=>errors.push(e.message));
    const goto=q=>page.goto(new URL(q,root).href);
    const top=async()=>{const b=await page.locator('.detail-hero h2').boundingBox();assert.ok(b.y>=0&&b.y<350,`title should be visible at ${width}: ${b.y}`);};
    await goto('?view=library');
    const card=page.locator('.browse-card [data-select="base:abyss-currency"]');
    await card.scrollIntoViewIfNeeded();
    const originalY=await page.evaluate(()=>scrollY); assert.ok(originalY>500);
    await card.click(); await top();
    await page.goBack(); await page.locator('.browse-card').first().waitFor();
    await page.waitForFunction(y=>Math.abs(scrollY-y)<4,originalY);
    if(width<=1000) await page.locator('[data-action="toggle-filters"]').click();
    await page.locator('#search').fill('심연');
    await card.scrollIntoViewIfNeeded(); const filteredY=await page.evaluate(()=>scrollY);
    await card.click(); await top();
    await page.goBack(); await page.locator('.browse-card').first().waitFor();
    assert.equal(await page.locator('#search').inputValue(),'심연');
    await page.waitForFunction(y=>Math.abs(scrollY-y)<4,filteredY);
    await card.click();
    await page.locator('[data-detail-section="sources"]').click();
    assert.ok(await page.evaluate(()=>scrollY)>500);
    await page.locator('#workspace-switch').click();
    await page.locator('#list [data-select="base:abyss-rare-equipment"]').click(); await top();
    await goto('?compare=abyss-currency&compare=abyss-rare-equipment&compare=delirium-rush');
    await page.locator('.comparison-table').waitFor();
    const rows=page.locator('tr[data-row]');
    assert.equal(await rows.first().locator('td').count(),3);
    assert.match(await page.locator('[data-row="options"]').innerText(),/속성 제한 없음/);
    assert.equal(await page.locator('[data-row="tablets"] details[open]').count(),0);
    if(width<700) {
      const a=await rows.first().locator('td').nth(0).boundingBox(),b=await rows.first().locator('td').nth(1).boundingBox();
      assert.ok(Math.abs(a.x-b.x)<1 && b.y>=a.y+a.height-1,'same item values must be vertically adjacent');
      assert.equal(await rows.first().locator('.mobile-comparison-name:visible').count(),3);
    }
    measurements.push({width,comparisonHeight:(await page.locator('.comparison-table').boundingBox()).height});
    await page.screenshot({path:`test-results/recheck-comparison-${width}.png`});
    await page.locator('#comparison-details').check();
    await page.locator('.comparison-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);
    await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));
    const detailButton=page.locator('.comparison-table [data-select]').first();
    await detailButton.scrollIntoViewIfNeeded();
    const comparisonPosition=await page.evaluate(()=>({y:scrollY,table:document.querySelector('.comparison-scroll').scrollTop}));
    await detailButton.click(); await top();
    await page.goBack(); await page.locator('.comparison-table').waitFor();
    await page.waitForFunction(p=>Math.abs(scrollY-p.y)<4 && Math.abs(document.querySelector('.comparison-scroll').scrollTop-p.table)<4,comparisonPosition);
    await detailButton.click(); await top();
    await page.locator('[data-action="play"]').first().click();
    assert.equal(await page.locator('.preparation-role:visible').count(),3);
    assert.match(await page.locator('.preparation-role').nth(2).innerText(),/속성 제한 없음/);
    assert.equal(await page.locator('[data-prepared]').count(),6,'3 tablets + waystone + atlas + masters; supplies are explanations');
    await page.locator('[data-prepared="0"]').check();
    await page.locator('[data-prepared="1"]').check();
    await page.locator('[data-repeat="0"]').check();
    await page.locator('#run-start-step').selectOption('1');
    await page.locator('[data-action="reset-play"]').click();
    assert.equal(await page.locator('[data-prepared="0"]').isChecked(),false);
    assert.equal(await page.locator('[data-prepared="1"]').isChecked(),true);
    assert.match(await page.locator('.current-step h3').innerText(),/2 \//);
    await page.locator('[data-action="leave-play"]').click();
    await page.locator('[data-action="play"]').first().click();
    assert.equal(await page.locator('[data-repeat="0"]').isChecked(),true);
    await page.reload(); await page.locator('[data-prepared="0"]').waitFor();
    assert.equal(await page.locator('[data-repeat="0"]').isChecked(),false);
    await goto('?view=library'); await page.locator('#new').click();
    const note=page.locator('#field-method-notes'), name=page.locator('#field-method-name');
    assert.equal(await name.evaluate(el=>el.selectionEnd-el.selectionStart), '새 파밍법'.length);
    const memoBox=await note.boundingBox(),actionBox=await page.locator('[data-note-to="supplies"]').boundingBox();
    measurements.push({width,memoY:memoBox.y,memoHeight:memoBox.height,actionBottom:actionBox.y+actionBox.height});
    if(width===960) assert.ok(actionBox.y+actionBox.height<720 && memoBox.height>=200,'memo and a structure action fit the first screen');
    await page.screenshot({path:`test-results/recheck-editor-${width}.png`});
    await name.fill('새 기록 시험'); await note.fill('메모에서 옮길 준비물\n남겨둘 메모');
    await note.evaluate(el=>el.setSelectionRange(0,11));
    await page.locator('[data-note-to="supplies"]').click();
    const selection=await note.evaluate(el=>[el.selectionStart,el.selectionEnd]);
    await page.locator('#note-copy-result button').click();
    await page.locator('#preview-dialog').waitFor({state:'visible'});
    assert.equal(await page.locator('#preview-body .panel').first().getAttribute('data-preview-panel'),'steps');
    assert.match(await page.locator('#preview-body .notice').innerText(),/미확인/);
    assert.equal(await page.locator('#preview-body [data-preview-panel="setup"]').count(),0);
    await page.locator('#preview-full').check();
    assert.equal(await page.locator('#preview-body [data-preview-panel="setup"]').count(),1);
    await page.keyboard.press('Escape');
    assert.deepEqual(await note.evaluate(el=>[el.selectionStart,el.selectionEnd]),selection);
    const memoPreview=page.locator('[data-preview-section="notes"]');
    await memoPreview.scrollIntoViewIfNeeded();
    const editorY=await page.evaluate(()=>scrollY);
    await memoPreview.click();
    assert.equal(await page.locator('#preview-body .panel').first().getAttribute('data-preview-panel'),'notes');
    assert.match(await page.locator('#preview-body .panel').first().innerText(),/남겨둘 메모/);
    await page.locator('#preview-dialog [data-close]').click();
    assert.ok(Math.abs(await page.evaluate(()=>scrollY)-editorY)<4,'preview restores editor scroll');
    assert.equal(await note.inputValue(),'메모에서 옮길 준비물\n남겨둘 메모');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.locator('[data-action="cancel-edit"]').first().click();
    assert.equal(await page.evaluate(()=>localStorage.getItem('poe2-farming.personal.v1')),null);
    await context.close();
  }
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify(measurements));
  console.log('PASS: R-01–06 navigation/back, preparation roles and selective reset, stacked comparison, compact notes and contextual preview');
} finally {await browser.close();}
