import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = process.env.APP_URL;
assert.ok(new URL(root).pathname === '/poe2-farming/', 'Release checks must run at the project subpath');
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_PATH ? { executablePath: process.env.BROWSER_PATH } : {}) });
const key = 'poe2-farming.personal.v1', errors = [], failed = [];
try {
  const context = await browser.newContext(), page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message));
  page.on('requestfailed', r => failed.push(r.url()));
  page.on('response', r => { if (r.url().startsWith(root) && r.status() >= 400) failed.push(r.url()); });
  await page.goto(root + '?method=azmeri-strongbox');
  await page.locator('.detail-hero h2').waitFor();
  assert.equal(await page.getByRole('button', { name: '원본 편집', exact: true }).count(), 0);
  assert.equal(await page.locator('.detail-panel[open]').count(), 5);
  await page.locator('#tablets > summary').click();
  assert.equal(await page.locator('#tablets > .detail-panel-body').isVisible(), false);
  await page.locator('[data-detail-section="tablets"]').click();
  assert.equal(await page.locator('#tablets > .detail-panel-body').isVisible(), true);
  await page.locator('[data-action="share"]').click();
  assert.equal(new URL(await page.locator('#share-url').inputValue()).pathname, '/poe2-farming/');
  await page.keyboard.press('Escape');
  await page.locator('[data-action="copy"]').click();
  await page.locator('[data-path="method.notes"]').fill('공개 전 백업 복원 검증');
  await page.locator('[data-action="finish"]').first().click();
  await page.locator('[data-action="edit"]').waitFor();
  const saved = await page.evaluate(k => JSON.parse(localStorage.getItem(k)), key);
  const downloading = page.waitForEvent('download'); await page.locator('#export').click();
  const backup = await downloading;
  const fresh = await browser.newContext(), restore = await fresh.newPage();
  await restore.goto(root); await restore.locator('#import').click();
  await restore.locator('#backup-file').setInputFiles(await backup.path());
  await restore.locator('#confirm-import').click();
  await restore.locator('[data-action="edit"]').waitFor();
  assert.deepEqual(await restore.evaluate(k => JSON.parse(localStorage.getItem(k)), key), saved);
  await restore.reload(); await restore.locator('#import').waitFor();
  assert.deepEqual(await restore.evaluate(k => JSON.parse(localStorage.getItem(k)), key), saved);
  for (const path of ['src/local-admin.js', 'scripts/serve.mjs', 'data/library-overrides.ko.json', '__admin/session']) assert.equal((await fetch(root + path)).status, 404);
  assert.equal((await fetch(new URL('/__admin/session', root))).status, 404);
  assert.deepEqual(errors, []); assert.deepEqual(failed, []);
  console.log('PASS: project subpath assets, collapsible sections, shared URL, original edit excluded, backup/restore on a fresh browser and private endpoints absent');
} finally { await browser.close(); }
