import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { gunzipSync } from 'node:zlib';
import { waystoneEffects } from '../src/waystones.js';
import { editorData } from '../src/editor-data.js';
import { tradeData } from '../src/trade-data.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_PATH ? { executablePath: process.env.BROWSER_PATH } : {}) });
const root = process.env.APP_URL || 'http://127.0.0.1:4173/';
const key = 'poe2-farming.personal.v1', errors = [];
const omen = editorData.modifiers.find(m => m.metric === 'omenChance');
const waystone = waystoneEffects.find(m => m.family === 'MapMonsterFireDamage');
const decode = url => JSON.parse(gunzipSync(Buffer.from(new URL(url).pathname.split('/').at(-1), 'base64url')));
try {
  for (const mobile of [false, true]) {
    const context = await browser.newContext({ viewport: mobile ? { width: 390, height: 844 } : { width: 1440, height: 1000 }, isMobile: mobile, hasTouch: mobile });
    const page = await context.newPage(); page.setDefaultTimeout(10000); page.on('pageerror', e => errors.push(e.message));
    const stored = () => page.evaluate(k => JSON.parse(localStorage.getItem(k)), key);
    await page.goto(new URL('?view=library', root).href);
    await page.getByRole('button', { name: '새 파밍법' }).click();
    await page.getByLabel('파밍법 이름 (필수)').fill('거래소 검색 테스트');
    await page.locator('[data-op="add-tablet"]').click();
    await page.getByLabel('공식 서판 명칭', { exact: true }).selectOption('의식 서판');
    await page.getByLabel('서판 속성 추가', { exact: true }).selectOption(omen.id);
    await page.locator('[data-path="method.tablets.items.0.options.0.priority"]').selectOption('required');
    await page.locator('[data-path="method.tablets.items.0.options.0.min"]').fill('60');
    await page.locator('[data-op="add-tablet"]').click();
    await page.getByLabel('공식 서판 명칭', { exact: true }).nth(1).selectOption('탐험 서판');
    const unsupported = editorData.modifiers.find(m => m.tablets.includes('탐험 서판') && !tradeData.mappings[m.id]);
    await page.getByLabel('서판 속성 추가', { exact: true }).nth(1).selectOption(unsupported.id);
    await page.getByLabel('경로석 속성 추가', { exact: true }).selectOption(waystone.id);
    await page.locator('[data-path="method.waystone.options.0.priority"]').selectOption('required');
    await page.locator('[data-path="method.waystone.tier"]').selectOption('16');
    await page.locator('[data-path="method.waystone.affixCount"]').selectOption('8');
    await page.locator('[data-path="method.waystone.corrupted"]').selectOption('false');
    await page.getByRole('button', { name: '저장', exact: true }).first().click();
    const saved = await stored(), dialog = page.locator('#trade-dialog'), link = page.locator('#trade-open');
    const ready = () => link.waitFor({ state: 'visible' });
    const close = () => page.getByRole('button', { name: '거래소 검색 창 닫기' }).click();
    await page.locator('[data-trade="tablet"]').first().click(); await ready();
    assert.equal(await page.locator('#trade-league').inputValue(), 'Forbidden Rites');
    let url = await link.getAttribute('href'), q = decode(url);
    assert.equal(q.type, '의식 서판'); assert.equal(q.stats[0].filters[0].value.min, 60);
    assert.equal(await link.getAttribute('rel'), 'noopener noreferrer');
    // Clipboard runs only on explicit click; URL creation does not write or mutate saved data.
    await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async text => { window.copiedTrade = text; } } }));
    await page.locator('#trade-copy').click();
    assert.equal(await page.evaluate(() => window.copiedTrade), url);
    await page.locator('[data-trade-condition]').uncheck(); await ready();
    assert.deepEqual(decode(await link.getAttribute('href')).stats, [{ type: 'and', filters: [] }]);
    await page.locator('[data-trade-condition]').check(); await ready();
    await page.locator('#trade-league').selectOption('custom');
    await page.locator('#trade-error').waitFor({ state: 'visible' });
    assert.equal(await link.isVisible(), false); assert.equal(await page.locator('#trade-copy').isDisabled(), true);
    await page.locator('#trade-custom').fill('Hardcore Forbidden Rites'); await ready();
    assert.match(await link.getAttribute('href'), /Hardcore%20Forbidden%20Rites/);
    assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth), true);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await dialog.screenshot({ path: `test-results/trade-${mobile ? 'mobile' : 'desktop'}.png` });
    await page.keyboard.press('Escape'); assert.equal(await dialog.isVisible(), false);
    await page.locator('[data-trade="tablet"]').nth(1).click(); await ready();
    assert.equal(decode(await link.getAttribute('href')).type, '탐험 서판');
    assert.equal(await page.locator('[data-trade-condition]').isDisabled(), true);
    assert.match(await dialog.innerText(), /거래소 속성 연결 미확인/);
    await close();
    await page.locator('[data-trade="waystone"]').click(); await ready();
    q = decode(await link.getAttribute('href'));
    assert.deepEqual(q.filters.map_filters.filters.map_tier, { min: 16, max: 16 });
    assert.equal(q.filters.misc_filters.filters.corrupted.option, 'false');
    assert.equal(q.stats.at(-1).filters[0].value.min, 8);
    assert.equal(q.stats[0].filters[0].id, tradeData.mappings[waystone.variantIds[0]].ids[0]);
    await close(); assert.deepEqual(await stored(), saved);
    await page.getByRole('button', { name: '세팅 편집' }).click();
    await page.locator('[data-path="method.tablets.items.0.options.0.min"]').fill('75');
    await page.getByRole('button', { name: '저장', exact: true }).first().click();
    await page.reload();
    await page.locator('[data-trade="tablet"]').first().click(); await ready();
    assert.equal(decode(await link.getAttribute('href')).stats[0].filters[0].value.min, 75);
    await close();
    await page.goto(new URL('?method=tablet-drop', root).href);
    await page.locator('[data-trade="waystone"]').click(); await ready();
    assert.equal(await page.locator('.trade-missing').count(), 0);
    assert.equal(decode(await link.getAttribute('href')).filters.map_filters.filters.map_bonus.min, 100);
    await context.close();
  }
  assert.deepEqual(errors, []);
  console.log('PASS: saved tablet/waystone URLs, latest league/custom league, condition toggles, unsupported notice, clipboard, edit/reload, unchanged personal records, keyboard and mobile layout');
} finally { await browser.close(); }
