import { preparationItems } from './usability.js';
export function renderPlay(entry, state, { esc, rich, list, evidence }) {
  const m = entry.method, items = preparationItems(m);
  const preparation = (repeat) => items.map((item, i) => ({item,i})).filter(({i}) => state.repeat.includes(i) === repeat).map(({item,i}) => `<div class="preparation-item"><label><input type="checkbox" data-prepared="${i}" ${state.checked.includes(i) ? 'checked' : ''}><span>${esc(item.text)}</span></label>${item.role ? `<p class="preparation-role">${rich(item.role)}</p>` : ''}${item.notes?.length ? `<div class="preparation-notes"><strong>${item.trade === 'tablet' ? '서판 전체' : '경로석'} 준비 설명</strong>${list(item.notes)}</div>` : ''}${item.details.length ? `<details><summary>전체 조건 보기</summary>${list(item.details)}</details>` : ''}<div class="preparation-actions">${item.trade ? `<button data-trade="${item.trade}" data-index="${item.index || 0}">거래소 검색 ↗</button>` : ''}<label><input type="checkbox" data-repeat="${i}" ${repeat ? 'checked' : ''}>다음 판 다시 확인</label></div></div>`).join('') || `<p class="muted">${repeat ? '지정한 항목 없음 · 판마다 확인할 준비에서 ‘다음 판 다시 확인’을 선택하세요.' : '모든 항목을 이번 판 준비로 지정했습니다.'}</p>`;
  return `<div class="detail-hero"><div><h2>${esc(m.name)}</h2><p>준비·진행 · 출처 패치 ${esc(m.patch || '미확인')}</p></div><button data-action="leave-play">세팅 상세로 돌아가기</button></div>
    <p class="form-help">체크와 현재 단계는 이 탭을 닫거나 새로고침하면 초기화됩니다. 개인 세팅과 백업에는 포함하지 않습니다.</p>
    ${state.changed ? '<p class="notice">세팅이 바뀌어 이전 완료 표시를 초기화했습니다.</p>' : ''}
    <section class="panel"><h3>준비 확인 <span id="preparation-count" role="status">${state.checked.length} / ${items.length}</span></h3>
    <p class="form-help">기본은 확인 상태를 유지합니다. 판마다 다시 확인할 항목을 직접 지정하세요. 소모 여부를 자동으로 판단하지 않습니다.</p><div class="preparation-list"><section aria-label="이번 판 준비"><h4>이번 판 준비 · ${state.round}판째</h4>${preparation(true)}</section><section aria-label="유지할 준비"><h4>유지할 준비</h4>${preparation(false)}</section><details><summary>대안·준비 메모</summary>${list(m.tablets.notes)}</details></div></section>
    <section class="panel current-step"><h3>현재 단계 · ${m.steps.length ? `${state.step + 1} / ${m.steps.length}` : '미확인'}</h3><p class="active-step">${rich(m.steps[state.step] || '등록된 진행 순서가 없습니다. 세팅과 출처를 먼저 확인하세요.')}</p><div class="hero-actions"><button data-play-step="-1" ${state.step === 0 ? 'disabled' : ''}>이전 단계</button><button data-play-step="1" ${state.step >= m.steps.length - 1 ? 'disabled' : ''}>다음 단계</button><button data-action="reset-play">다음 판 시작</button></div><p class="form-help">다음 판: 이번 판 준비 ${state.repeat.length}개만 체크 해제 · 유지할 준비는 그대로 · ${m.steps.length ? `${state.startStep + 1}단계부터` : '진행 순서 미확인'}</p>${m.steps.length ? `<label class="field">다음 판 시작 단계<select id="run-start-step">${m.steps.map((s,i) => `<option value="${i}" ${i === state.startStep ? 'selected' : ''}>${i+1}. ${esc(s)}</option>`).join('')}</select></label><p class="form-help">준비가 포함된 원본 순서를 유지합니다. 반복할 때 준비 단계를 건너뛰려면 시작 단계를 선택하세요.</p>` : ''}<details><summary>전체 순서와 근거</summary>${list(m.steps)}${evidence(m.executionEvidence)}</details></section>
    <section class="panel"><h3>중단 조건·주의점</h3>${list(m.stopConditions, '등록된 중단 조건 없음 · 임의의 기준을 적용하지 마세요.')}<ul>${m.constraints.map(c => `<li>${rich(c.text)}</li>`).join('')}</ul><details><summary>미확인 사항</summary>${list(m.unresolved)}</details></section>`;
}
